# This is a basic workflow to help you get started with Actions

name: Create pull request after merge

on:
  push:
    branches: [main, acceptance, test]
jobs:
  merge_job_to_acceptance:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Create Pull Request from test to acceptance
          uses: peter-evans/create-pull-request@v4
          with:
            token: ${{ secrets.GH_TOKEN }}
            commit-message: Auto Pull Request
            title: Your desired title
            body: Auto-created Pull Request
            branch: ${{ github.head_ref }}
            base: acceptance