# This is a basic workflow to help you get started with Actions

name: Create pull request after merge

on:
  pull_request:
    types: [closed]
jobs:
  create_PR_to_acceptance:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: echo vars
          run: |
            echo "base-ref=${{ github.base_ref }}"
        - name: Create Pull Request from test to acceptance
          if: ${{ github.base_ref == 'test' }}
          uses: peter-evans/create-pull-request@v4
          with:
            token: ${{ secrets.GH_TOKEN }}
            commit-message: Auto Pull Request
            title: Your desired title
            body: Auto-created Pull Request
            branch: ${{ github.head_ref }}
            base: acceptance